### ISSUE TITLE
Documentación en wiki

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIQ_2021-multijuegos#6]
**Fecha** : 28 de mayo

**Comment by maikadelsol** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/80331111/119956291-3bde5b00-bfa1-11eb-899c-dc6f4cedbce4.png)

**Comment by maikadelsol** [comment]
[Trabajo informatica_Comentado.zip](https://github.com/aigora/twIQ_2021-multijuegos/files/6561111/Trabajo.informatica_Comentado.zip)

**Comment by estherglez02** [comment]
[https://github.com/aigora/twIQ_2021-multijuegos/wiki](url)
